FROM base:latest

ARG USER

WORKDIR /data/www

COPY ./www /data/www

RUN useradd -m -d /data/www -s /bin/bash -u 1000 user

COPY ./php/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY ./php/php-fpm.conf /usr/local/etc/php-fpm.conf
COPY ./php/project.ini /usr/local/etc/php/conf.d/project.ini

EXPOSE 22

CMD ["php-fpm"]
